{{- if $.Values.global.render -}}
{{- range $key, $val := $.Values.apps }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.resource.namespace }} 
  {{- if $.Values.global.argocd.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  {{- end }}
spec:
  host: {{ $key }}
  trafficPolicy:
    tls:
      mode: {{ $.Values.mesh.trafficPolicy }}
  subsets:
  {{- range $ver, $ker := $val }}
  - name: {{ $ker.version }}
    labels:
      version: {{ $ker.version }}
  {{- end }}
{{- end }}
{{- end -}}